# Generated by Django 2.2.6 on 2019-10-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('admno', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=5)),
                ('house', models.CharField(max_length=10)),
                ('sclass', models.IntegerField()),
                ('event1', models.CharField(max_length=20)),
                ('event2', models.CharField(max_length=20)),
            ],
        ),
    ]
