# Generated by Django 2.2.6 on 2019-11-04 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0003_pointstable_medals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointstable',
            old_name='medals',
            new_name='medal',
        ),
    ]
