# Generated by Django 2.2.4 on 2008-07-30 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0004_auto_20191104_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointstable',
            name='medal',
        ),
    ]
