# Generated by Django 2.2.4 on 2008-07-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0005_remove_pointstable_medal'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default='NULL', max_length=6),
        ),
        migrations.AddField(
            model_name='student',
            name='ssec',
            field=models.CharField(default='NULL', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='event1',
            field=models.CharField(default='NULL', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='event2',
            field=models.CharField(default='NULL', max_length=20),
        ),
    ]
