# Generated by Django 2.2.4 on 2008-07-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0006_auto_20080731_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='event3',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='house',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
